---
- hosts: mitaka-14-controller
  vars:
    - controller_host: mitaka-14-controller
  roles:
    - controller/common
#    - controller/glance
  environment:
    OS_URL: "{{keystone_admin_url}}"
    OS_IDENTITY_API_VERSION: 3
    OS_TOKEN: "{{keystone_admin_token}}"
    OS_AUTH_URL: "http://{{controller_host}}:35357/v3"
