---
- apt: name=software-properties-common state=latest
#sudo add-apt-repository cloud-archive:mitaka
#- apt_repository: repo='cloud-archive:mitaka'
- apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/mitaka main'
- apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=5EDB1B62EC4926EA
- apt: update_cache=yes upgrade=dist cache_valid_time=86400
- apt: name=python-openstackclient state=latest

- apt:
    state: present
    name:
      - mariadb-server
      - python-pymysql

- copy:
    dest: /etc/mysql/conf.d/openstack.cnf
    content: |
      [mysqld]
      bind-address = {{controller_host}}
      default-storage-engine = innodb
      innodb_file_per_table
      collation-server = utf8_general_ci
      character-set-server = utf8

- service: name=mysql state=restarted

#- shell: mysql_secure_installation

- apt:
    state: present
    name:
      - mongodb-server
      - mongodb-clients
      - python-pymongo

- lineinfile:
    dest: /etc/mongodb.conf
    regexp: "bind_ip =.*"
    line: "bind_ip = {{ controller_host }}"

- lineinfile:
    dest: /etc/mongodb.conf
    line: smallfiles = true

- service: name=mongodb state=stopped
- shell: rm -f /var/lib/mongodb/journal/prealloc.*
- service: name=mongodb state=started

- apt:
    name: rabbitmq-server
    state: latest

- rabbitmq_user:
    user: openstack
    password: "{{nova_rabbit_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- apt:
    state: present
    name:
      - memcached
      - python-memcache

- lineinfile:
    dest: /etc/memcached.conf
    regexp: "^(.*)-l 127.0.0.1(.*)$"
    line: "\\1-l {{ controller_host }}\\2"
    backrefs: yes

- service: name=memcached state=restarted

- apt: name=python-mysqldb state=present

- mysql_db:
    name: keystone
    state: present

- mysql_user: name=keystone password={{keystone_mysql_password}} priv=keystone.*:ALL,GRANT host=localhost state=present
- mysql_user: name=keystone password={{keystone_mysql_password}} priv=keystone.*:ALL,GRANT host=% state=present

- copy: dest=/etc/init/keystone.override  content="manual"

- apt:
    state: present
    name:
      - keystone
      - apache2
      - libapache2-mod-wsgi

- lineinfile:
    dest: /etc/keystone/keystone.conf
    regexp: "admin_token =.*"
    line: "admin_token = {{keystone_admin_token}}"

- lineinfile:
    dest: /etc/keystone/keystone.conf
    regexp: "^connection = (.*)"
    line: "connection = mysql+pymysql://keystone:{{keystone_mysql_password}}@{{controller_host}}/keystone"
    backrefs: yes

- lineinfile:
    dest: /etc/keystone/keystone.conf
    regexp: "^#*.*provider ="
    line: "provider = fernet"

- apt:
    state: present
    name: python-pexpect

- shell: su -s /bin/sh -c "keystone-manage db_sync" keystone

- shell: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- lineinfile:
    dest: /etc/apache2/apache2.conf
    regexp: "^#*.*ServerName"
    line:  "ServerName {{controller_host}}"

- copy:
    dest: /etc/apache2/sites-available/wsgi-keystone.conf
    content: |
      Listen 5000
      Listen 35357

      <VirtualHost *:5000>
          WSGIDaemonProcess keystone-public processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP}
          WSGIProcessGroup keystone-public
          WSGIScriptAlias / /usr/bin/keystone-wsgi-public
          WSGIApplicationGroup %{GLOBAL}
          WSGIPassAuthorization On
          ErrorLogFormat "%{cu}t %M"
          ErrorLog /var/log/apache2/keystone.log
          CustomLog /var/log/apache2/keystone_access.log combined

          <Directory /usr/bin>
              Require all granted
          </Directory>
      </VirtualHost>

      <VirtualHost *:35357>
          WSGIDaemonProcess keystone-admin processes=5 threads=1 user=keystone group=keystone display-name=%{GROUP}
          WSGIProcessGroup keystone-admin
          WSGIScriptAlias / /usr/bin/keystone-wsgi-admin
          WSGIApplicationGroup %{GLOBAL}
          WSGIPassAuthorization On
          ErrorLogFormat "%{cu}t %M"
          ErrorLog /var/log/apache2/keystone.log
          CustomLog /var/log/apache2/keystone_access.log combined

          <Directory /usr/bin>
              Require all granted
          </Directory>
      </VirtualHost>

- file:
    dest: /etc/apache2/sites-enabled/wsgi-keystone.conf
    src:  /etc/apache2/sites-available/wsgi-keystone.conf
    state: link

- service:
    name: keystone
    state: started

- service:
    name: apache2
    state: restarted

- file:
    dest: /var/lib/keystone/keystone.db
    state: absent

# These are not idempotent!
- shell: openstack service create --name keystone --description "OpenStack Identity" identity
- shell: openstack endpoint create --region RegionOne identity public http://{{controller_host}}:5000/v3
- shell: openstack endpoint create --region RegionOne identity internal http://{{controller_host}}:5000/v3
- shell: openstack endpoint create --region RegionOne identity admin http://{{controller_host}}:35357/v3
